version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-vl:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-vl:/data

  wemo-testdb:
    image: mysql:latest
    container_name: ${TEST_DB_CONTAINER_NAME}  # testDB 컨테이너 이름
    ports:
      - ${TEST_DB_PORT}:3306  # 테스트 DB 포트
    restart: always
    environment:
      MYSQL_DATABASE: ${TEST_DB_NAME}  # 테스트 DB 이름
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}  # 테스트 DB 루트 비밀번호
    volumes:
      - testdb-vl:/var/lib/mysql  # 테스트 DB 볼륨

  # 블루-그린 배포를 위한 Wemo 서비스들
  app-blue:
    image: 0304ohyeryung/wemo:latest
    container_name: wemo-blue
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    networks:
      - wemo-network
    depends_on:
      - redis

  app-green:
    image: 0304ohyeryung/wemo:latest
    container_name: wemo-green
    ports:
      - "8082:8080"
    env_file:
      - ./.env
    networks:
      - wemo-network
    depends_on:
      - redis

volumes:
  mysql-vl:
    driver: local
  redis-vl:
    driver: local
  wemo-testdb-vl:
    driver: local  # 테스트 DB 볼륨
